# Generated by Django 5.2.3 on 2025-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_new', '0002_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
