# Generated by Django 5.2.3 on 2025-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_new', '0003_userprofile_avatar_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='lesson_resources/'),
        ),
    ]
